version: '3.3'
services:
  db:
    build: ./docker/postgres
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: example
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    command: 'postgres -c config_file="/etc/postgresql/postgresql.conf"'
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/conf.d:/etc/postgresql
      - ./log/postgres:/var/log/postgresql

